// Generated by CoffeeScript 1.10.0
var printStderr, printStdout, stdErrStr, stderrCallback;

importScripts('ffmpeg-20160403.js' + '?' + Math.random());

printStdout = function(text) {
  return postMessage({
    type: 'stdout',
    data: text
  });
};

printStderr = function(text) {
  return postMessage({
    type: 'stderr',
    data: text
  });
};

stdErrStr = '';

stderrCallback = function(chr) {
  var frame;
  if (chr !== null) {
    stdErrStr += String.fromCharCode(chr);
  }
  frame = stdErrStr.match(/frame=\s*(\d+)[^\d]$/);
  if (frame) {
    postMessage({
      type: 'frame',
      data: +frame[1]
    });
  }
  if (chr === 10 || chr === null) {
    printStderr(stdErrStr.trimRight());
    return stdErrStr = '';
  }
};

this.onmessage = function(event) {
  var opts;
  opts = {
    "arguments": event.data["arguments"],
    memory: event.data.memory,
    files: event.data.files,
    print: printStdout,
    stderr: stderrCallback
  };
  postMessage({
    type: 'starting',
    data: opts["arguments"]
  });
  return ffmpeg_run(opts, function(result) {
    var error, movieBuffer;
    movieBuffer = result.buffer;
    try {
      return postMessage({
        type: event.data.returnType,
        data: movieBuffer
      }, [movieBuffer]);
    } catch (error) {
      return postMessage({
        type: event.data.returnType,
        data: movieBuffer
      });
    }
  });
};

//# sourceMappingURL=canvasmovieworker.js.map
