// Generated by CoffeeScript 1.10.0
this['ffmpeg_run'] = function(opts, callback) {
  var Module, args;
  args = opts['arguments'];
  Module = {
    "arguments": args,
    "TOTAL_MEMORY": opts['memory']
  };
  Module['preRun'] = [
    function() {
      var file, fileData;
      FS.init(opts['stdin'], opts['stdout'], opts['stderr']);
      while (file = opts['files'].pop()) {
        fileData = new Uint8Array(file['data']);
        FS.writeFile(file['name'], fileData, {
          encoding: 'binary'
        });
      }
      return null;
    }
  ];
  Module['postRun'] = [
    function() {
      var outputFile, outputFilePath;
      outputFilePath = args.pop();
      outputFile = FS.readFile(outputFilePath, {
        encoding: 'binary'
      });
      callback(outputFile);
      return null;
    }
  ];
